#!/usr/bin/env bash

git init

npm init -y

# createdb $1

# aws ec2 run-instances --launch-template LaunchTemplateId=lt-04ac4128672edaa62,Version=1 >> ec2Instance.json

node deployInit.js

# npm i

# npm run start-dev

